### PR TITLE
update translation-pull-request workflows

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

- update `create-translation-pull-request-v4.yml` to use 4.4-dev branch
- add `create-translation-pull-request-v5.yml` to support 5.0-dev branch
- update node-version to v18 to match CMS

I think for J4 there is a second branch necessary (proposal: `translation_v4`) and should fork from 4.4-dev; branch `translation` is already updated to 5.0-dev

@HLeithner

### CODE REVIEW

**Comment by heelc29** [comment]
@HLeithner Is this the right approach?

**Comment by HLeithner** [comment]
Looks good, but I didn't had the time to look at this topic. Also there is a problem in the concept.

**Comment by heelc29** [comment]
Ok. Thanks

**Comment by heelc29** [comment]
@HLeithner I've created an alternative PR https://github.com/joomla-translation-bot/joomla-cms/pull/3 to support only the current major version of Joomla or is there a concept now?

**Pull request closed without merging**
