### PR TITLE
[4.x] update translation-pull-request workflows

### PR DESCRIPTION
**Pull request by heelc29**
Changes:
- update `create-translation-pull-request-v4.yml`
  - scheduled workflow [work only on default branch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule)
  >Scheduled workflows run on the latest commit on the default or base branch. 

@HLeithner @wilsonge

### CODE REVIEW

**Comment by HLeithner** [comment]
it shouldn't run on pull request, no direct changes to this repo should be made

**Comment by heelc29** [comment]
> it shouldn't run on pull request, no direct changes to this repo should be made

@HLeithner I'm not sure what you mean - in this comment you wrote to update the workflow in this repo https://github.com/joomla/joomla-cms/pull/39066#issuecomment-1300001983.

At the moment no translation update for J4.x is performed because scheduled actions are executed in the default branch (current `translation5`)
image

**Comment by HLeithner** [comment]
github actions are annoying, I will convert this to drone at some point... j4 installer shouldn't get any language changes anymore anyway... I keep it open so I don't forget.

**Comment by HLeithner** [comment]
I'm closing this for now, changing it to variables makes more sense. thanks for the pr

**Pull request closed without merging**
